services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"

      - "8080:8080"
      - "8000:8000"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers.conf:/etc/nginx/servers.conf
      - ./load_balancer.conf:/etc/nginx/load_balancer.conf
      - ./fastcgi_learning.conf:/etc/nginx/fastcgi_learning.conf
      - ./cache_learning.conf:/etc/nginx/cache_learning.conf
      - ./server_https.conf:/etc/nginx/server_https.conf

      - ./logs:/etc/nginx/logs
      - ./index.html:/var/www/html/index.html
      - ./performance/index.html:/var/www/html/performance/index.html
      - ./performance/birthday.png:/var/www/html/performance/birthday.png
      - ./performance/css:/var/www/html/performance/css
      - ./performance/js:/var/www/html/performance/js
      - ./certs:/etc/nginx/certs

      - ./erro.html:/var/www/html/erro.html
    networks:
      - app

  php:
    image: php:fpm
    volumes:
      - ./php/index.php:/var/www/html/index.php
    networks:
      - app

networks:
  app:
    driver: bridge
